- name: "configuration play." 
  hosts: webservers
  user: ec2-user
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 120 seconds for target connection to become reachable/usable."
      wait_for_connection:
         timeout: 120

    - name: Install python for Ansible
      become: true
      dnf:
        name: python3
        state: present 



  roles:
    - configure-server
    - configure-prometheus-node-exporter
