- name: "configuration play." 
  hosts: webservers
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 120 seconds for target connection to become reachable/usable."
      wait_for_connection:
         timeout: 120

    - name: Install python for Ansible
      become: true
      apt:
        name: python3
        update_cache: yes 

  # environment: 
  #   - TYPEORM_CONNECTION: postgres
  #   #"{{ lookup('env', 'TYPEORM_CONNECTION')}}"
  #   - TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
  #   #"{{ lookup('env', 'TYPEORM_ENTITIES')}}"
  #   - TYPEORM_HOST: database-1.csub2uflo81x.us-east-1.rds.amazonaws.com
  #   #"{{ lookup('env', 'TYPEORM_HOST')}}"
  #   - TYPEORM_PORT: 5432
  #   - TYPEORM_USERNAME: postgres
  #   #"{{ lookup('env', 'TYPEORM_USERNAME')}}"
  #   - TYPEORM_PASSWORD: 12345678
  #   #"{{ lookup('env', 'TYPEORM_PASSWORD')}}"
  #   - TYPEORM_DATABASE: my1stdb
  #   #"{{ lookup('env', 'TYPEORM_DATABASE')}}"
  #   - TYPEORM_MIGRATIONS: ./src/migrations/*.ts
  #   #"{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
  #   - TYPEORM_MIGRATIONS_DIR: ./src/migrations
  #   #"{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"

  roles:
    - configure-server
  
