# - name: "copy files"
#   template:
#     src: "files/back-end"
#     dest: "~/"

# - name: "unzip files"
#   shell: |
#     tar -xzvf artifact.tar.gz

- name: extract artifact
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: .

- name: start applications
  become: yes
  shell: |
    export ENVIRONMENT=develpment
    export TYPEORM_ENTITIES=".src/modules/domain/**/*.entity.js"
    export TYPEORM_MIGRATIONS=".src/migrations/*.js"
    export TYPEORM_MIGRATIONS_DIR=".src/migrations"
    export TYPEORM_CONNECTION="postgres"
    export TYPEORM_HOST="database-1.csub2uflo81x.us-east-1.rds.amazonaws.com"
    export TYPEORM_USERNAME="postgres"
    export TYPEORM_PASSWORD="12345678"
    export TYPEORM_DATABASE="my1stdb"
    export TYPEORM_PORT=5432
    sudo npm install
    sudo pm2 stop default
    sudo pm2 start npm -- start
  # args:
  #   chdir: /home/ubuntu/dist


# - name: "start app"
#   shell: |
    
#     sudo npm install
#     sudo pm2 stop default
#     #sudo pm2 start npm --name "udapeople-backend" -- run start
#     sudo pm2 start npm -- start

  # # environment:
  #   ENVIRONMENT: production
  #   NODE_ENV: production
  #   TYPEORM_CONNECTION: postgres
  #   TYPEORM_MIGRATIONS_DIR: ./src/migrations
  #   TYPEORM_ENTITIES: ./src/modules/**/*.entity.ts
  #   TYPEORM_MIGRATIONS: ./src/migrations/*.ts
  #   TYPEORM_HOST: database-1.csub2uflo81x.us-east-1.rds.amazonaws.com
  #   TYPEORM_PORT: 5432
  #   TYPEORM_USERNAME: postgres
  #   TYPEORM_PASSWORD: 12345678
  #   TYPEORM_DATABASE: my1stdb

# - name: "Set pm2 start as service"
#   become: yes
#   shell: |
#     sudo env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu

# - name: check pm2 status
#   become: yes
#   shell: |
#     pm2 describe "udapeople-backend"
#   register: command_output_npm
# - debug: var=command_output_npm.stdout_lines    

