- name: Ensure required packages are installed
  yum:
    name: tar
    state: present

- name: Download node exporter tarball
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.8.1/node_exporter-1.8.1linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move node exporter binary to /usr/local/bin
  become: true
  copy:
    src: /tmp/node_exporter-1.8.1.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0777'

- name: Copy node exporter service file to systemd
  become: true
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Enable and start node exporter service
  become: true
  systemd:
    name: node_exporter
    enabled: yes
    state: started
    daemon_reload: yes

# - name: "install node exporter."
#   unarchive:
#     src: https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
#     dest: /tmp
#     remote_src: yes

# - name: "move binary to /usr/local/bin."
#   become: true
#   copy:
#     src: /tmp/node_exporter-0.17.0.linux-amd64/node_exporter
#     dest: /usr/local/bin/node_exporter
#     remote_src: yes
#     mode: '0777'
    
# - name: "add node exporter configuration."
#   become: true
#   copy:
#     src: node_exporter.service
#     dest: /etc/systemd/system/

# - name: "enable node_exporter service"
#   become: true
#   systemd:
#     state: restarted
#     daemon_reload: yes
#     name: node_exporter
#     enabled: yes